-- Optional: load the demo apothecary into a newly created Supabase project.
insert into public.products(name,slug,description,benefits,how_to_use,price,category,image_url,stock,is_featured) values
('Moringa Leaf','moringa-leaf','Carefully dried moringa leaves with a fresh, earthy aroma. A versatile pantry staple for teas and nourishing meals.','Naturally rich in plant nutrients. Traditionally enjoyed as part of a balanced diet.','Steep one teaspoon in hot water for 5 minutes, or stir into soups and smoothies.',8500,'leaves','https://images.unsplash.com/photo-1516594798947-e65505dbb29d?auto=format&fit=crop&w=900&q=85',28,true),
('Ashwagandha Root','ashwagandha-root','Whole, gently dried roots with a deep, grounding character, sourced for traditional herbal preparations.','A time-honoured botanical for everyday wellness routines.','Simmer a small piece in water for 10 minutes, then strain.',12000,'roots','https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=900&q=85',16,true),
('Neem Leaves','neem-leaves','Distinctive aromatic leaves selected and dried with care for traditional use.','A cherished botanical with a long history in West African herbal traditions.','Prepare a light infusion. Seek qualified guidance for personal use.',6500,'leaves','https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=900&q=85',35,true),
('Ginger Root','ginger-root','Warm, fragrant ginger root with a bright and gently spicy finish.','A familiar kitchen botanical enjoyed around the world.','Slice into hot water, tea, soups or everyday cooking.',5000,'roots','https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=900&q=85',42,true),
('Zobo (Hibiscus)','hibiscus-zobo','Deep ruby hibiscus petals for a vivid, tart infusion, served hot or chilled.','Naturally colourful and caffeine-free.','Steep in hot water, then strain. Add ginger or citrus to taste.',7000,'leaves','https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=900&q=85',38,true),
('Turmeric Powder','turmeric-powder','Golden ground turmeric with a mellow warmth and earthy fragrance.','A classic spice for colourful cooking and traditional blends.','Stir into soups, stews, warm milk or golden tea.',6000,'powders','https://images.unsplash.com/photo-1615485500704-8e990f9900f2?auto=format&fit=crop&w=900&q=85',25,false),
('Moringa Powder','moringa-powder','Fine moringa leaf powder, gently processed for easy everyday use.','An easy way to add a leafy botanical to your pantry.','Begin with half a teaspoon in a smoothie or warm water.',9000,'powders','https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=85',19,false),
('Fennel Seeds','fennel-seeds','Sweet, aromatic seeds selected for a fresh, clean flavour.','Traditionally enjoyed as a fragrant after-meal infusion.','Lightly crush a teaspoon and steep in hot water.',4500,'mixtures','https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=900&q=85',52,false),
('Licorice Root','licorice-root','Naturally sweet root pieces for slow-steeped herbal tea blends.','A traditional botanical with a distinctive, mellow sweetness.','Simmer a small piece in water. Consult a health professional before use.',7500,'roots','https://images.unsplash.com/photo-1504545102780-26774c1bb073?auto=format&fit=crop&w=900&q=85',18,false),
('Clove Buds','clove-buds','Whole aromatic clove buds, carefully selected for deep fragrance.','A warming, versatile botanical used in food and traditional preparations.','Add a few whole buds to tea, broths and spice blends.',5500,'mixtures','https://images.unsplash.com/photo-1603905179139-d6b33c4bbf61?auto=format&fit=crop&w=900&q=85',30,false),
('Moringa Seeds','moringa-seeds','Dried moringa seeds from the mighty tree, packed and handled with care.','A traditional seed with a distinctive place in botanical culture.','Use only as directed by a qualified health professional.',8000,'mixtures','https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=900&q=85',14,false),
('Peppermint Leaves','peppermint-leaves','Cooling, fragrant leaves for a fresh, caffeine-free cup.','A refreshing herbal infusion for any time of day.','Steep one teaspoon in hot water for 4–6 minutes.',6000,'leaves','https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?auto=format&fit=crop&w=900&q=85',33,false)
on conflict (slug) do nothing;
